# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt UI\OpenScope.ui'
#
# Created: Fri Apr 12 15:27:22 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 580)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("OpenScope")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 871, 546))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-5, 0, 791, 41))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background: rgb(170, 0, 0) url(images/button.png) no-repeat center;")
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setText("")
        self.label.setObjectName("label")
        self.ch2_settings = QtGui.QGroupBox(self.frame)
        self.ch2_settings.setGeometry(QtCore.QRect(650, 190, 122, 136))
        self.ch2_settings.setAutoFillBackground(True)
        self.ch2_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.ch2_settings.setObjectName("ch2_settings")
        self.ch2_settings_Layout = QtGui.QGridLayout(self.ch2_settings)
        self.ch2_settings_Layout.setObjectName("ch2_settings_Layout")
        self.ch2_resolution = QtGui.QDial(self.ch2_settings)
        self.ch2_resolution.setCursor(QtCore.Qt.PointingHandCursor)
        self.ch2_resolution.setStyleSheet("handle{color: rgb(255, 0, 0);}")
        self.ch2_resolution.setTracking(True)
        self.ch2_resolution.setWrapping(False)
        self.ch2_resolution.setNotchesVisible(True)
        self.ch2_resolution.setObjectName("ch2_resolution")
        self.ch2_settings_Layout.addWidget(self.ch2_resolution, 2, 0, 1, 3)
        self.ch2_offset = QtGui.QToolButton(self.ch2_settings)
        self.ch2_offset.setMinimumSize(QtCore.QSize(45, 23))
        self.ch2_offset.setObjectName("ch2_offset")
        self.ch2_settings_Layout.addWidget(self.ch2_offset, 3, 0, 1, 1)
        self.ch2_probe = QtGui.QToolButton(self.ch2_settings)
        self.ch2_probe.setMinimumSize(QtCore.QSize(45, 23))
        self.ch2_probe.setObjectName("ch2_probe")
        self.ch2_settings_Layout.addWidget(self.ch2_probe, 3, 1, 1, 1)
        self.hor_settings = QtGui.QGroupBox(self.frame)
        self.hor_settings.setGeometry(QtCore.QRect(605, 50, 166, 136))
        self.hor_settings.setAutoFillBackground(True)
        self.hor_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.hor_settings.setFlat(False)
        self.hor_settings.setCheckable(False)
        self.hor_settings.setChecked(False)
        self.hor_settings.setObjectName("hor_settings")
        self.generator_Layout = QtGui.QGridLayout(self.hor_settings)
        self.generator_Layout.setObjectName("generator_Layout")
        self.time_base = QtGui.QDial(self.hor_settings)
        self.time_base.setCursor(QtCore.Qt.PointingHandCursor)
        self.time_base.setNotchesVisible(True)
        self.time_base.setObjectName("time_base")
        self.generator_Layout.addWidget(self.time_base, 0, 0, 1, 1)
        self.freq_generator = QtGui.QGroupBox(self.frame)
        self.freq_generator.setGeometry(QtCore.QRect(525, 400, 246, 131))
        self.freq_generator.setAutoFillBackground(True)
        self.freq_generator.setStyleSheet("QLabel {background-color: rgb(255, 255, 255);}")
        self.freq_generator.setObjectName("freq_generator")
        self.freq_display = QtGui.QLCDNumber(self.freq_generator)
        self.freq_display.setGeometry(QtCore.QRect(10, 30, 161, 41))
        self.freq_display.setCursor(QtCore.Qt.IBeamCursor)
        self.freq_display.setAutoFillBackground(False)
        self.freq_display.setStyleSheet("QLCDNumber {background-color:rgba(165, 170, 107, 150)}")
        self.freq_display.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.freq_display.setSmallDecimalPoint(False)
        self.freq_display.setDigitCount(7)
        self.freq_display.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.freq_display.setProperty("value", 0.0)
        self.freq_display.setProperty("intValue", 0)
        self.freq_display.setObjectName("freq_display")
        self.freq_dial = QtGui.QDial(self.freq_generator)
        self.freq_dial.setGeometry(QtCore.QRect(190, 20, 50, 64))
        self.freq_dial.setCursor(QtCore.Qt.PointingHandCursor)
        self.freq_dial.setWrapping(True)
        self.freq_dial.setObjectName("freq_dial")
        self.freq_shape = QtGui.QToolButton(self.freq_generator)
        self.freq_shape.setGeometry(QtCore.QRect(15, 90, 75, 23))
        self.freq_shape.setObjectName("freq_shape")
        self.freq_range = QtGui.QToolButton(self.freq_generator)
        self.freq_range.setGeometry(QtCore.QRect(100, 90, 75, 23))
        self.freq_range.setObjectName("freq_range")
        self.scope_start = QtGui.QToolButton(self.frame)
        self.scope_start.setGeometry(QtCore.QRect(525, 60, 75, 23))
        self.scope_start.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("images/on.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.scope_start.setIcon(icon1)
        self.scope_start.setCheckable(True)
        self.scope_start.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.scope_start.setObjectName("scope_start")
        self.scope_function = QtGui.QToolButton(self.frame)
        self.scope_function.setGeometry(QtCore.QRect(525, 85, 75, 23))
        self.scope_function.setObjectName("scope_function")
        self.ch1_settings = QtGui.QGroupBox(self.frame)
        self.ch1_settings.setGeometry(QtCore.QRect(525, 190, 122, 136))
        self.ch1_settings.setAutoFillBackground(True)
        self.ch1_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_settings.setObjectName("ch1_settings")
        self.ch1_settings_Layout = QtGui.QGridLayout(self.ch1_settings)
        self.ch1_settings_Layout.setObjectName("ch1_settings_Layout")
        self.ch1_offset = QtGui.QToolButton(self.ch1_settings)
        self.ch1_offset.setMinimumSize(QtCore.QSize(45, 23))
        self.ch1_offset.setObjectName("ch1_offset")
        self.ch1_settings_Layout.addWidget(self.ch1_offset, 3, 0, 1, 1)
        self.ch1_resolution = QtGui.QDial(self.ch1_settings)
        self.ch1_resolution.setCursor(QtCore.Qt.PointingHandCursor)
        self.ch1_resolution.setStyleSheet("handle {rgb(85, 255, 0)}")
        self.ch1_resolution.setTracking(True)
        self.ch1_resolution.setWrapping(False)
        self.ch1_resolution.setNotchesVisible(True)
        self.ch1_resolution.setObjectName("ch1_resolution")
        self.ch1_settings_Layout.addWidget(self.ch1_resolution, 2, 0, 1, 3)
        self.ch1_probe = QtGui.QToolButton(self.ch1_settings)
        self.ch1_probe.setMinimumSize(QtCore.QSize(45, 23))
        self.ch1_probe.setObjectName("ch1_probe")
        self.ch1_settings_Layout.addWidget(self.ch1_probe, 3, 1, 1, 2)
        self.scope_display = ScopeView(self.frame)
        self.scope_display.setGeometry(QtCore.QRect(5, 45, 512, 420))
        self.scope_display.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scope_display.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scope_display.setSceneRect(QtCore.QRectF(0.0, 0.0, 512.0, 420.0))
        self.scope_display.setCacheMode(QtGui.QGraphicsView.CacheBackground)
        self.scope_display.setViewportUpdateMode(QtGui.QGraphicsView.BoundingRectViewportUpdate)
        self.scope_display.setObjectName("scope_display")
        self.LSA_trigger = QtGui.QGroupBox(self.frame)
        self.LSA_trigger.setGeometry(QtCore.QRect(525, 330, 246, 66))
        self.LSA_trigger.setObjectName("LSA_trigger")
        self.ch3_set = QtGui.QPushButton(self.LSA_trigger)
        self.ch3_set.setGeometry(QtCore.QRect(10, 25, 26, 23))
        self.ch3_set.setText("0")
        self.ch3_set.setShortcut("")
        self.ch3_set.setCheckable(True)
        self.ch3_set.setObjectName("ch3_set")
        self.ch4_set = QtGui.QPushButton(self.LSA_trigger)
        self.ch4_set.setGeometry(QtCore.QRect(40, 25, 26, 23))
        self.ch4_set.setText("1")
        self.ch4_set.setShortcut("")
        self.ch4_set.setCheckable(True)
        self.ch4_set.setObjectName("ch4_set")
        self.ch5_set = QtGui.QPushButton(self.LSA_trigger)
        self.ch5_set.setGeometry(QtCore.QRect(70, 25, 26, 23))
        self.ch5_set.setText("2")
        self.ch5_set.setShortcut("")
        self.ch5_set.setCheckable(True)
        self.ch5_set.setObjectName("ch5_set")
        self.ch6_set = QtGui.QPushButton(self.LSA_trigger)
        self.ch6_set.setGeometry(QtCore.QRect(100, 25, 26, 23))
        self.ch6_set.setText("3")
        self.ch6_set.setShortcut("")
        self.ch6_set.setCheckable(True)
        self.ch6_set.setObjectName("ch6_set")
        self.ch7_set = QtGui.QPushButton(self.LSA_trigger)
        self.ch7_set.setGeometry(QtCore.QRect(130, 25, 26, 23))
        self.ch7_set.setText("4")
        self.ch7_set.setShortcut("")
        self.ch7_set.setCheckable(True)
        self.ch7_set.setObjectName("ch7_set")
        self.lsa_trigger = QtGui.QPushButton(self.LSA_trigger)
        self.lsa_trigger.setGeometry(QtCore.QRect(165, 25, 75, 23))
        self.lsa_trigger.setObjectName("lsa_trigger")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.ch2_settings.setTitle(QtGui.QApplication.translate("MainWindow", "CH2", None, QtGui.QApplication.UnicodeUTF8))
        self.ch2_offset.setText(QtGui.QApplication.translate("MainWindow", "DC", None, QtGui.QApplication.UnicodeUTF8))
        self.ch2_probe.setText(QtGui.QApplication.translate("MainWindow", "x1", None, QtGui.QApplication.UnicodeUTF8))
        self.hor_settings.setTitle(QtGui.QApplication.translate("MainWindow", "Time base", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_generator.setTitle(QtGui.QApplication.translate("MainWindow", "Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_shape.setText(QtGui.QApplication.translate("MainWindow", "Sinus", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_range.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.scope_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.scope_function.setText(QtGui.QApplication.translate("MainWindow", "Scope", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1_settings.setTitle(QtGui.QApplication.translate("MainWindow", "CH1", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1_offset.setText(QtGui.QApplication.translate("MainWindow", "DC", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1_probe.setText(QtGui.QApplication.translate("MainWindow", "x1", None, QtGui.QApplication.UnicodeUTF8))
        self.LSA_trigger.setTitle(QtGui.QApplication.translate("MainWindow", "LSA", None, QtGui.QApplication.UnicodeUTF8))
        self.lsa_trigger.setText(QtGui.QApplication.translate("MainWindow", "Trigger", None, QtGui.QApplication.UnicodeUTF8))

from scopeview import ScopeView
